FROM golang:1.12.7
WORKDIR $GOPATH/src/github.com/victorguru/perkbox
COPY . .
RUN export GO111MODULE=on && go get -d -v ./...
# RUN go install -v ./...
RUN export GO111MODULE=on && go install -v ./...
CMD ["perkbox"]